version: "3.0"

services:
  db:
    image: mongo:latest
    container_name: db
    env_file: ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    volumes:
      - ./persistence/db:/data/db
  redis:
    image: redis:latest
    container_name: redis
    env_file: ./.env
    command: "redis-server --requirepass $REDIS_PASSWORD"
    volumes:
      - ./persistence/redis:/data
  backend:
    build: .
    container_name: backend
    env_file: ./.env
    depends_on:
      - db
      - redis
    ports:
      - 80:3000

volumes:
  db:
  redis:
