version: "3.0"

services:
  db0:
    image: mongo:latest
    container_name: db0
    hostname: db0
    env_file: ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    volumes:
      - ./persistence/db0:/data/db
    # entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]


  redis:
    image: redis:latest
    container_name: redis
    env_file: ./.env
    command: "redis-server --requirepass $REDIS_PASSWORD"
    volumes:
      - ./persistence/redis:/data


  backend:
    build: .
    container_name: backend
    env_file: ./.env
    depends_on:
      - db0
      - redis
    ports:
      - 80:3000
      - 443:3443

volumes:
  db:
  redis:
